# This is default sample specification
# Feel free to change it
pluginName: EC-NewJIRA
description: No description
version: 1.0.0
author: No Name
supportUrl: No support URL
category: Utilities

# This is a declaration for the plugin configuration
configuration:
  # Shell to be used for checking connection
  shell: ec-perl
  parameters:
   - name: config
     type: entry
     label: Configuration Name
     required: true
     documentation: The name for the created configuration
   - name: credential
     type: credential
     label: Credential
     userNameLabel: Username
     required: true
     passwordLabel: Password
   - name: httpProxyUrl
     type: entry
     label: HTTP proxy Address
     required: false
     documentation: A url that should be used as proxy URL.
   - name: proxy_credential
     type: credential
     label: Proxy Credential
     userNameLabel: Username
     required: true
     passwordLabel: Password
   - name: debugLevel
     label: Debug Level
     type: select
     required: 0
     value: 0
     options:
       - name: Info
         value: 0
       - name: Debug
         value: 1
       - name: Trace
         value: 2

procedures:
- name: Get Issue
  description: Gets issue by its id
  hasConfig: true # configuration field will be generated automatically
  parameters:
  - name: issueId
    documentation: An id for jira issue to be retrieved.
    type: entry
    required: true
    label: Issue ID
  outputParameters:
    issue: An issue details
  # Steps are not defined so we assume that this is one-step procedure with a single step named Deploy
  shell: ec-perl
